# Generated by Django 5.0.2 on 2024-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
